# -*- mode: python ; coding: utf-8 -*-
# Generated by tools/build_exe.py -- change that tool, not this file (it gets overwritten).

# Only the assets the app really reads: PetArt loads pet_meta.json + anim/, the ico is for
# the window. assets/layers (intermediate cut-outs), the static portraits, the exported jpg
# files and the source SVG stay out of the package.
DATAS = [
    ('D:/temp/dswhale_eatfreerice/github/assets/pet/pet_meta.json', 'assets/pet'),
    ('D:/temp/dswhale_eatfreerice/github/assets/pet/anim', 'assets/pet/anim'),
    ('D:/temp/dswhale_eatfreerice/github/assets/dswhale_pet.ico', 'assets'),
]

# PyQt5 modules the pet never uses (it only needs QtCore / QtGui / QtWidgets)
EXCLUDES = [
    'PyQt5.QtWebEngine', 'PyQt5.QtWebEngineCore', 'PyQt5.QtWebEngineWidgets', 'PyQt5.QtQml',
    'PyQt5.QtQuick', 'PyQt5.QtQuick3D', 'PyQt5.QtQuickWidgets', 'PyQt5.QtMultimedia',
    'PyQt5.QtMultimediaWidgets', 'PyQt5.QtSql', 'PyQt5.QtTest', 'PyQt5.QtDesigner',
    'PyQt5.QtHelp', 'PyQt5.QtOpenGL', 'PyQt5.QtXml', 'PyQt5.QtXmlPatterns',
    'PyQt5.QtSvg', 'PyQt5.QtPrintSupport', 'PyQt5.QtBluetooth', 'PyQt5.QtNfc',
    'PyQt5.QtPositioning', 'PyQt5.QtLocation', 'PyQt5.QtSensors', 'PyQt5.QtSerialPort',
    'PyQt5.QtWebChannel', 'PyQt5.QtWebSockets', 'PyQt5.QtDBus', 'PyQt5.QtAxContainer',
    'PyQt5.QtCharts', 'PyQt5.QtDataVisualization', 'PyQt5.QtNetworkAuth', 'PyQt5.QtRemoteObjects',
    'PyQt5.QtTextToSpeech', 'PyQt5.QtWinExtras', 'tkinter', 'unittest',
    'pydoc', 'doctest', 'sqlite3', 'lib2to3',
    'distutils', 'setuptools', 'wheel', 'pip',
]

# After collection, drop the big Qt pieces we never use (the pet only paints with QPainter,
# so none of these ever get loaded on Windows)
DROP_BINARIES = [
    'opengl32sw.dll', 'd3dcompiler_47.dll', 'libegl.dll', 'libglesv2.dll',
    'qt5quick', 'qt5qml', 'qmltooling', 'qtquick', 'qml/',
]

a = Analysis(
    ['D:/temp/dswhale_eatfreerice/github/dswhale_pet.py'],
    pathex=[],
    binaries=[],
    datas=DATAS,
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=EXCLUDES,
    noarchive=False,
    optimize=0,
)
a.binaries = TOC([e for e in a.binaries
                  if not any(k in e[0].lower() for k in DROP_BINARIES)])
pyz = PYZ(a.pure)

COMMON = dict(debug=False, bootloader_ignore_signals=False, strip=False, upx=True,
              upx_exclude=[], runtime_tmpdir=None, console=False,
              disable_windowed_traceback=False, argv_emulation=False, target_arch=None,
              codesign_identity=None, entitlements_file=None, icon=['D:/temp/dswhale_eatfreerice/github/assets/dswhale_pet.ico'])

# one-file build: unpacks to %TEMP% on every start
exe = EXE(pyz, a.scripts, a.binaries, a.datas, [],
          name='dswhale_pet', **COMMON)
