"""Build the desktop pet into an exe -- a thin wrapper around PyInstaller.

One file, no console, icon included. **Only the assets the app really reads** are bundled
(`assets/pet/pet_meta.json`, `assets/pet/anim/`, `assets/dswhale_pet.ico`): `PetArt` loads its
images from exactly those places, so `assets/layers/` (intermediate cut-out files), the static
portraits, the exported `state_*.jpg` files and the source SVG stay out of the package -- the
megabytes that saves make no difference to whoever downloads it.

The `sys.frozen` branch in `dswhale_pet.py` makes the app read its assets from the unpack
directory, so **running from source and running the exe are the same code**, and the config stays
at `%APPDATA%\\dswhale_pet\\config.json` (upgrading never asks for the key again).

Usage:
    python tools/build_exe.py                # -> dist/dswhale_pet.exe (one file)
    python tools/build_exe.py --onedir       # folder build: starts fast (no unpacking), but you
                                             # have to copy the whole folder around
    python tools/build_exe.py --console      # keep the console so errors are visible (debugging)
    python tools/build_exe.py --name other-name

When it finishes it also pokes the Windows icon cache: Explorer remembers "path -> icon" far too
well, so after **overwriting** an exe in place it keeps showing the old icon for ages (the PE file
really does carry the new one).

Dependency: python -m pip install --upgrade pyinstaller
"""
from __future__ import annotations

import argparse
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

# The files the app really reads at runtime (do NOT copy `--add-data "assets;assets"` -- that drags
# 26 MB of intermediate files along)
DATAS = [
    ('assets/pet/pet_meta.json', 'assets/pet'),
    ('assets/pet/anim', 'assets/pet/anim'),
    ('assets/dswhale_pet.ico', 'assets'),
]

# PyQt5 submodules that are never used: each one dropped here takes a pile of Qt DLLs with it
# (the pet only needs QtCore / QtGui / QtWidgets)
EXCLUDES = [
    'PyQt5.QtWebEngine', 'PyQt5.QtWebEngineCore', 'PyQt5.QtWebEngineWidgets',
    'PyQt5.QtQml', 'PyQt5.QtQuick', 'PyQt5.QtQuick3D', 'PyQt5.QtQuickWidgets',
    'PyQt5.QtMultimedia', 'PyQt5.QtMultimediaWidgets', 'PyQt5.QtSql', 'PyQt5.QtTest',
    'PyQt5.QtDesigner', 'PyQt5.QtHelp', 'PyQt5.QtOpenGL', 'PyQt5.QtXml',
    'PyQt5.QtXmlPatterns', 'PyQt5.QtSvg', 'PyQt5.QtPrintSupport', 'PyQt5.QtBluetooth',
    'PyQt5.QtNfc', 'PyQt5.QtPositioning', 'PyQt5.QtLocation', 'PyQt5.QtSensors',
    'PyQt5.QtSerialPort', 'PyQt5.QtWebChannel', 'PyQt5.QtWebSockets', 'PyQt5.QtDBus',
    'PyQt5.QtAxContainer', 'PyQt5.QtCharts', 'PyQt5.QtDataVisualization',
    'PyQt5.QtNetworkAuth', 'PyQt5.QtRemoteObjects', 'PyQt5.QtTextToSpeech',
    'PyQt5.QtWinExtras',
    'tkinter', 'unittest', 'pydoc', 'doctest', 'sqlite3', 'lib2to3', 'distutils',
    'setuptools', 'wheel', 'pip',
]


def make_spec(spec_path, entry, name, datas, icon, onedir, console):
    """Write a spec file: datas whitelist + PyQt5 module excludes + binary filtering.

    Why a spec instead of command line flags: `--exclude-module` only blocks Python modules, it
    cannot block the **big binaries** on the Qt side (Mesa software rendering `opengl32sw.dll`
    alone is 20 MB, the ANGLE D3D backend, the whole Qml/Quick family). Those have to be filtered
    out of `a.binaries` after `Analysis` ran.
    """
    L = []
    A = L.append
    A('# -*- mode: python ; coding: utf-8 -*-')
    A('# Generated by tools/build_exe.py -- change that tool, not this file (it gets overwritten).')
    A('')
    A('# Only the assets the app really reads: PetArt loads pet_meta.json + anim/, the ico is for')
    A('# the window. assets/layers (intermediate cut-outs), the static portraits, the exported jpg')
    A('# files and the source SVG stay out of the package.')
    A('DATAS = [')
    for src, dest in datas:
        A('    (%r, %r),' % (src.replace('\\', '/'), dest))
    A(']')
    A('')
    A('# PyQt5 modules the pet never uses (it only needs QtCore / QtGui / QtWidgets)')
    A('EXCLUDES = [')
    for i in range(0, len(EXCLUDES), 4):
        A('    ' + ', '.join(repr(m) for m in EXCLUDES[i:i + 4]) + ',')
    A(']')
    A('')
    A('# After collection, drop the big Qt pieces we never use (the pet only paints with QPainter,')
    A('# so none of these ever get loaded on Windows)')
    A('DROP_BINARIES = [')
    A("    'opengl32sw.dll', 'd3dcompiler_47.dll', 'libegl.dll', 'libglesv2.dll',")
    A("    'qt5quick', 'qt5qml', 'qmltooling', 'qtquick', 'qml/',")
    A(']')
    A('')
    A('a = Analysis(')
    A('    [%r],' % entry.replace('\\', '/'))
    A('    pathex=[],')
    A('    binaries=[],')
    A('    datas=DATAS,')
    A('    hiddenimports=[],')
    A('    hookspath=[],')
    A('    hooksconfig={},')
    A('    runtime_hooks=[],')
    A('    excludes=EXCLUDES,')
    A('    noarchive=False,')
    A('    optimize=0,')
    A(')')
    A('a.binaries = TOC([e for e in a.binaries')
    A("                  if not any(k in e[0].lower() for k in DROP_BINARIES)])")
    A('pyz = PYZ(a.pure)')
    A('')
    A('COMMON = dict(debug=False, bootloader_ignore_signals=False, strip=False, upx=True,')
    A('              upx_exclude=[], runtime_tmpdir=None, console=%s,' % bool(console))
    A('              disable_windowed_traceback=False, argv_emulation=False, target_arch=None,')
    A('              codesign_identity=None, entitlements_file=None, icon=[%r])'
      % icon.replace('\\', '/'))
    A('')
    if onedir:
        A("# folder build: nothing to unpack at start, but you copy the whole folder around")
        A('exe = EXE(pyz, a.scripts, [], exclude_binaries=True,')
        A('          name=%r, **COMMON)' % name)
        A('coll = COLLECT(exe, a.binaries, a.datas, strip=False, upx=True,')
        A('               upx_exclude=[], name=%r)' % name)
    else:
        A('# one-file build: unpacks to %TEMP% on every start')
        A('exe = EXE(pyz, a.scripts, a.binaries, a.datas, [],')
        A('          name=%r, **COMMON)' % name)
    with open(spec_path, 'w', encoding='utf-8') as fp:
        fp.write('\n'.join(L) + '\n')


def refresh_icon_cache(exe):
    """Bump the exe's mtime, then ask Windows to refresh its icon cache.

    Why bother every time: Explorer caches "path -> icon", so after **overwriting** an exe in
    place it keeps showing the old icon for ages (the PE file already carries the new one).
    Touching the mtime invalidates that cache key, and `ie4uinit` gives it another nudge. If the
    icon still does not change you have to restart Explorer -- too noisy a step to do for the
    user, so pressing that button is left to them.
    """
    if os.name != 'nt':
        return
    try:
        os.utime(exe, None)
    except OSError:
        pass
    for flag in ('-show', '-ClearIconCache'):
        try:
            subprocess.run(['ie4uinit.exe', flag], stdout=subprocess.DEVNULL,
                           stderr=subprocess.DEVNULL, timeout=20)
        except (OSError, subprocess.SubprocessError):
            return


def main(argv=None):
    ap = argparse.ArgumentParser(description='build the desktop pet exe')
    ap.add_argument('--name', default='dswhale_pet', help='exe name (default: dswhale_pet)')
    ap.add_argument('--onedir', action='store_true',
                    help='folder build (starts fast); one file by default')
    ap.add_argument('--console', action='store_true', help='keep the console (to read errors)')
    ap.add_argument('--no-clean', action='store_true', help='keep the previous build files')
    args = ap.parse_args(argv)

    icon = os.path.join(ROOT, 'assets', 'dswhale_pet.ico')
    if not os.path.exists(icon):                 # none yet? make one, never fail the build on it
        sys.path.insert(0, HERE)
        try:
            import make_pet_icon
        except ImportError:                      # a copy with the build script but not the asset tools
            raise SystemExit('missing icon %s (the build needs it).\n'
                             'Copy assets/dswhale_pet.ico over, or run it once in a folder that '
                             'has tools/make_pet_icon.py and copy the result here.' % icon)
        make_pet_icon.main([])

    try:
        import PyInstaller.__main__ as pyi
    except ImportError:
        raise SystemExit('PyInstaller is missing: python -m pip install --upgrade pyinstaller')

    entry = os.path.join(ROOT, 'dswhale_pet.py')
    if not os.path.exists(entry):
        raise SystemExit('cannot find %s' % entry)

    datas, payload = [], 0
    for rel, dest in DATAS:
        p = os.path.join(ROOT, *rel.split('/'))
        if not os.path.exists(p):
            raise SystemExit('missing asset %s\nrun this first: python tools/make_pet_assets.py '
                             '(static portraits) / tools/make_pet_anim.py (frame animations)' % p)
        if os.path.isdir(p):
            for dirpath, _, files in os.walk(p):
                payload += sum(os.path.getsize(os.path.join(dirpath, f)) for f in files)
        else:
            payload += os.path.getsize(p)
        datas.append((p, dest))
    print('assets: %d entries, %.1f MB total (only what the app reads; the rest of %s stays out)' % (
        len(DATAS), payload / 1024.0 / 1024.0, 'assets/'))

    spec = os.path.join(ROOT, args.name + '.spec')
    make_spec(spec, entry, args.name, datas, icon, args.onedir, args.console)
    print('spec  %s (asset whitelist / module excludes / Qt binary filtering all live in it)'
          % os.path.relpath(spec, ROOT).replace(os.sep, '/'))

    out = (os.path.join(ROOT, 'dist', args.name, args.name + '.exe') if args.onedir
           else os.path.join(ROOT, 'dist', args.name + '.exe'))
    if os.path.exists(out):
        # PyInstaller deletes the previous exe before writing the new one, and a running pet holds
        # that file open (WinError 5) -- so say it plainly instead of dumping a raw traceback.
        try:
            os.remove(out)
        except OSError as e:
            raise SystemExit('cannot replace %s: %s\n'
                             'The pet is probably still running -- quit it (tray menu -> Quit), '
                             'then run this again.'
                             % (os.path.relpath(out, ROOT).replace(os.sep, '/'), e))

    cmd = [spec, '--noconfirm',
           '--distpath', os.path.join(ROOT, 'dist'),
           '--workpath', os.path.join(ROOT, 'build')]
    if not args.no_clean:
        cmd.append('--clean')
    print('building: python -m PyInstaller %s' % os.path.relpath(spec, ROOT).replace(os.sep, '/'))
    pyi.run(cmd)

    if os.path.exists(out):
        print('done: %s (%.1f MB)' % (
            os.path.relpath(out, ROOT).replace(os.sep, '/'),
            os.path.getsize(out) / 1024.0 / 1024.0))
        if not args.onedir:
            print('the one-file build unpacks to %%TEMP%% on every start (twenty-odd MB, so a cold '
                  'start costs 1-2 seconds); use --onedir if you want it instant.')
        refresh_icon_cache(out)
        print('also nudged the Explorer icon cache (it likes to hang on to the old icon when an exe '
              'is overwritten in place); if the old one still shows, restart Explorer.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
